version: '3'
services:
  db:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
  drupal:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-drupal
    ports:
      - "9667:80"
    volumes:
      - ./drupal:/app
    command: ./checkinstall
  gatsby:
    build:
      context: .
      dockerfile: Dockerfile-gatsby
    ports:
      - "9668:8000"
    environment:
      - NODE_ENV=dev
    working_dir: /app
    volumes:
      - ./gatsby:/app
    command: tail -f /dev/null
volumes:
  db_data:
